# Интервал сканирования подключенных USB-устройств.
check_interval: 3s

# Период, на который устройство блокируется от повторной прошивки после успешного завершения.
dfu_cooldown: 1h

# Максимальное количество одновременных операций прошивки.
max_concurrent_jobs: 10

# Настройки голосовых уведомлений.
notifications:
  enabled: true
  voice: "Milena"
  rate: 200